### ISSUE TITLE
Can this layer be used in a Node runtime environment?

### ISSUE THREAD

**Issue by benze** [lumigo-io/lambda-log-shipper#6]
Given that lambdas have to specify their execution runtime as a configuration, is there any way to get this Python-based lambda layer working with a Node lambda?  Or is this layer limited to only working with Python lambdas?

**Comment by saartochner** [comment]
Hi,
This lambda is not limited to any runtime - you should be able to use it with nodejs lambdas.

Let me know if it doesn't work for you 👍

**Comment by frangauthiercgi** [comment]
Hello @saartochner 

I tried the extension with a simple hello world function using the template provided by the serverless framework:
https://www.serverless.com/framework/docs/providers/aws/examples/hello-world/node/
and attached the layer by modifying my 
serverless.yml configuration
```
functions:
  hello:
    handler: handler.hello
    layers:
      - arn:aws:lambda:us-east-1:114300393969:layer:lumigo-log-shipper:2
```

Then, I get
`/opt/python-runtime/lang/bin/python3.7: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory` error at runtime

Any idea what might cause this?
Thanks
